---
title: "1. Beadchip summary"
output:
  html_document:
    code_folding: "hide"
    theme: simplex
---

```{r setup, include=FALSE}
# rmarkdown::render_site()
knitr::opts_chunk$set(echo = FALSE)
library(kableExtra)
library(formattable)

path <- log
```


```{r}
# Scan for beadchips in PATH
beadchips <- unique(stringr::str_split(pheno$basename, "_", simplify = T)[,1])

# Construct data frame
n <- length(beadchips)
log_df <- data.frame(Beadchip = beadchips,
                     Sample_count = rep(NA,n),
                     Probe_count = rep(NA,n),
                     Removed_sample_count = rep(NA,n))

files <- list.files(path, full.names = T)

if(sum(grepl('_log_data.Rdata',files))==1){
  load(files[grepl('_log_data.Rdata',files)])
  } else {
  files <- files[grepl('_log_data.Rdata',files)]
  
  for (f in files){
    load(f)
    
    if(f == files[1]){
    log_data_tmp <- log_data
    } else {
      
      for (x in 1:length(log_data_tmp)){
        log_data_tmp[[x]] <- c(log_data_tmp[[x]], log_data[[x]])
      }
    }
    
    log_data <- log_data_tmp
  }
  
}


log_df$Probe_count <- log_data$n_probes[1]


for (i in 1:nrow(log_df)){
  
  if(any(grepl(log_df$Beadchip[i], log_data$rm_sample_list))){
    tmp <- log_data$rm_sample_list[grepl(log_df$Beadchip[i], log_data$rm_sample_list)]
    log_df$Sample_count[i] <- 8-length(tmp)
    log_df$Removed_sample_count[i] <- paste0(length(tmp), " (",
                                          length(tmp)/8*100, "%)")
    } else {
    log_df$Sample_count[i] <- 8
    log_df$Removed_sample_count[i] <- "0 (0%)"
  }
  
}

colnames(log_df) <- c('Beadchip',
                      'Samples',
                      'Probes',
                      'Removed samples')

# kable(log_df)%>%
#   kable_styling(bootstrap_options = c("striped", "hover"))

x <- log_df |> 
  formattable(list(
              Beadchip = formatter("span",
                                   style = x ~ style(color = ifelse(log_df$Samples == 8, "seagreen", "palevioletred"))),
              Samples = formatter("span", 
                                           x ~ icontext(ifelse(x == 8, "ok", "remove"),
                                                        x), 
                                           style = x ~ style(color = ifelse(x == 8, "seagreen", "palevioletred")))))

as.datatable(x, rownames = FALSE,
             options = list(pageLength = 10))
```

## List of removed samples

```{r}
rm <- pheno[match(log_data$rm_sample_list, pheno$basename),]

rm |> 
  dplyr::filter(!is.na(basename)) |> 
  DT::datatable()
```

