---
title: "3. Array intensities"
output:
  html_document:
    code_folding: "hide"
    theme: lumen
---

```{r setup, include=FALSE}
# rmarkdown::render_site()
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(plotly)
library(kableExtra)

path <- log
```

This page shows raw fluorescence intensities of samples prior to correction and beta value conversion.

## Plot of median intensities

```{r,echo=FALSE,message=FALSE, warning = FALSE}
input_dir_list <- dir(path)
plates <- plates

qc_merged <- NULL
rm_samples <- NULL
for(p in plates){
   load(paste(path,'/',p,'_qc.Rdata',sep=''))
   qc_merged <- rbind(qc_merged,qc)
   
   load(paste(path,'/',p,'_log_data.Rdata',sep=''))
   rm_samples <- c(rm_samples, log_data$rm_sample_list)
}

qc_merged <- as.data.frame(qc_merged) |> 
  tibble::rownames_to_column("basename") |> 
  dplyr::mutate(removed = ifelse(basename %in% na.omit(rm_samples), 
                                 "removed", "retained"))

# save merged QC
save(qc_merged, file = paste(path, '/qc_merged.Rdata'))

p <- qc_merged |> 
  ggplot(aes(x = mMed, y = uMed,
             colour = removed,
             text = basename)) +
  geom_point(size = 0.9, alpha = 0.8) +
  coord_cartesian(xlim = c(0, 20),
                  ylim = c(0, 20)) +
  geom_abline(slope = 1, intercept = 1, linetype = "dashed",
              colour = "gray40") +
  theme_minimal()

plotly::ggplotly(p)
```

## List of removed samples

* Any samples below 9.5 median intensity
* Samples flagged by lab team
* Samples with too many failed probes

```{r}
ind <- match(rm_samples[!is.na(rm_samples)],rownames(qc_merged))

if (length(ind)>0){
   kable(qc_merged[ind,])%>%
  kable_styling(bootstrap_options = c("striped", "hover"))   
}
```
