---
title: "5. Signal-to-noise"
output:
  html_document:
    code_folding: "hide"
    theme: simplex
---

```{r setup, include=FALSE}
# rmarkdown::render_site()
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(ggplot2)
library(dplyr)
library(plotly)
library(tibble)

# Remove previously failed samples from rho
rho <- rho[!rownames(rho) %in% log_data$rm_sample_list,]

# If pheno exists, can use pheno - otherwise use rho
if(exists("pheno") & "plate" %in% colnames(pheno)){
  tmp <- pheno |> 
    dplyr::filter(!basename %in% log_data$rm_sample_list)
  
  rows <- length(unique(tmp$plate))
  if(round(rows) == 0){
    rows <- 1
  }
  height = rows*3.5
} else {
  x <- rho |>
  tibble::rownames_to_column("basename") |>
  mutate(sentrix = stringr::str_split(basename, "_", simplify = TRUE)[,1]) 

  rows <- length(unique(x$sentrix))/3
  if(round(rows) == 0){
    rows <- 1
  }
  height = rows*3.5
}
```


# Plots {.tabset .tabset-fade}

## Density plot

```{r fig.align = "center", fig.width = 8, fig.height = 4}
p <- rho |> 
  tibble::rownames_to_column("basename") |>
  mutate(sentrix = stringr::str_split(basename, "_", simplify = TRUE)[,1]) |> 
  ggplot(aes(x = rho,
             colour = sentrix)) +
  geom_density(bw = 0.2) +
  theme_minimal() +
  theme(legend.position = "none")

ggplotly(p)

if(rows > 20){
  p <- rho |> 
    tibble::rownames_to_column("basename") |>
    mutate(plate = stringr::str_split(basename, "_", simplify = TRUE)[,1]) |>
    ggplot(aes(x = rho)) +
    geom_density(bw = 0.2) +
    theme_minimal() +
    theme(legend.position = "none") +
    ggtitle("Overall distribution")

  ggplotly(p)
}

if(exists("tmp") && "plate" %in% colnames(tmp)) {
  p <- tmp |> 
    ggplot(aes(x = rho,
               colour = plate)) +
    geom_density(bw = 0.2) +
    theme_minimal() +
    theme(legend.position = "none")

  ggplotly(p)
}
```

## Violin plot

```{r fig.align = "center"}
rho |> 
    tibble::rownames_to_column("basename") |>
    mutate(plate = stringr::str_split(basename, "_", simplify = TRUE)[,1]) |>
  ggplot(aes(x = plate,
             y = rho,
             colour = plate)) +
  ggdist::stat_pointinterval(size = 0.3) +
  # geom_boxplot(width = 0.5,
  #              outlier.shape = NA) +
  # geom_violin(aes(fill = plate)) +
  # geom_boxplot(width = 0.1) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) 

if(exists("tmp") && "plate" %in% colnames(tmp)) {
  
  tmp1 <- tmp |> 
    dplyr::group_by(plate) |> 
    dplyr::summarise(plate = unique(plate),
                     y = max(rho))
  
  
  tmp |> 
    ggplot(aes(x = plate,
               y = rho,
               colour = plate,
               label = plate)) +
  ggdist::stat_pointinterval(size = 0.3) +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())  +
    ggrepel::geom_label_repel(data = tmp1,
                              x = 1:length(unique(tmp1$plate)),
                              y = tmp1$y,
                              label = tmp1$plate,
                              alpha = 0.7)
                              
  }


```

## Individual samples

```{r fig.align = "center", fig.width = 10, fig.height=height}
if(exists("tmp") && "plate" %in% colnames(tmp)) {
  x <- tmp |>
  ggplot(aes(x = basename,
             y = rho)) +
  geom_point(aes(colour = plate)) +
  theme(legend.position = "bottom",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  facet_wrap(~plate,
             scales = "free_x",
             nrow = ceiling(rows))
  ggplotly(x)

  } else {
    x <- rho |>
  tibble::rownames_to_column("basename") |>
  mutate(plate = stringr::str_split(basename, "_", simplify = TRUE)[,1]) |>
  ggplot(aes(x = basename,
             y = rho)) +
  geom_point(aes(colour = plate)) +
  theme(legend.position = "bottom",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  facet_wrap(~plate,
             scales = "free_x",
             nrow = ceiling(rows))

ggplotly(x)
}
```


