---
title: "2. Array intensities"
output:
  html_document:
    code_folding: "hide"
    theme: lumen
---

```{r setup, include=FALSE}
# rmarkdown::render_site()
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
library(plotly)
library(kableExtra)

path <- log
```

This page shows raw fluorescence intensities of samples prior to correction and beta value conversion.

## Plot of median intensities

```{r,echo=FALSE,message=FALSE, warning = FALSE}
qc_df <- as.data.frame(qc) |> 
  tibble::rownames_to_column("basename") |> 
  dplyr::mutate(QC = ifelse(basename %in% na.omit(log_data$rm_sample_list), 
                                 "removed", "retained"))

p <- qc_df |> 
  ggplot(aes(x = mMed, y = uMed,
             colour = QC,
             text = basename)) +
  geom_point(size = 0.9, alpha = 0.8) +
  coord_cartesian(xlim = c(0, 20),
                  ylim = c(0, 20)) +
  geom_abline(slope = 1, intercept = 1, linetype = "dashed",
              colour = "gray40") +
  theme_minimal()

plotly::ggplotly(p)
```

## List of removed samples

* Any samples below 9.5 median intensity
* Samples flagged by lab team
* Samples with too many failed probes

```{r}
ind <- match(log_data$rm_sample_list[!is.na(log_data$rm_sample_list)],qc_df$basename)

if (length(ind)>0){
   kable(qc_df[ind,])%>%
  kable_styling(bootstrap_options = c("striped", "hover"))   
}
```
