# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "mapping_compatible_v1v2", # <mapping_compatible_v1v2>
  "IlmnID", # <mapping_compatible_v1v2>
  "EPICv1_Loci", # <mapping_compatible_v1v2>
  NULL
))
